### ISSUE TITLE
你自己测试过，可以正常使用吗？

### ISSUE THREAD

**Issue by ziwux** [meooxx/jd_yuyue#1]

**Comment by ziwux** [comment]
能不能把说明写的再详细点，不熟悉node，谢谢！

**Comment by meooxx** [comment]
https://github.com/zhou-xiaojun/jd_mask
不熟悉node 上面链接是 python版的， 挺好的。
我这就是增加了几个特定功能 比如说 扫码登录， 多进程任务。
目前功能是ok ，每天在用。 但是jd狗东西好像分地区供货， 目前有网友 在广东， 川渝地区🈶️抢到。
相关配置， 马上会简化
