### ISSUE TITLE
windows用户福利, 引导式配置

### ISSUE THREAD

**Issue by gzlee1985** [meooxx/jd_yuyue#32]
这个  里面yuyue-setup-amd64.exe   怎么用的？

**Comment by meooxx** [comment]
> 这个  里面yuyue-setup-amd64.exe   怎么用的？

双击执行就行了

**Comment by gzlee1985** [comment]
32  64  都下载 都是显示报错

**Comment by meooxx** [comment]
> 32 64 都下载 都是显示报错

现在俩个版本都是linux 编译出来的，不一定通用， 你加下tg， 发下cpu 和系统信息，针对性编译一个版本
或者自己使用gocode 代码自己编译一个

**Comment by gzlee1985** [comment]
老机器了   
Time of this report: 12/10/2021, 17:21:09
       Machine name: PCOS-2021DXAKES
   Operating System: Windows 7 旗舰版 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr_escrow.200102-1707)
           Language: Chinese (Simplified) (Regional Setting: Chinese (Simplified))
System Manufacturer: MICRO-STAR INTERNATIONAL CO.,LTD
       System Model: MS-7549
               BIOS: Default System BIOS
          Processor: AMD Phenom(tm) FX-5000 Quad-Core Processor (4 CPUs), ~2.2GHz
             Memory: 4096MB RAM
Available OS Memory: 4096MB RAM
          Page File: 4500MB used, 3688MB available
        Windows Dir: C:\Windows
    DirectX Version: DirectX 11
DX Setup Parameters: Not found
   User DPI Setting: Using System DPI
 System DPI Setting: 96 DPI (100 percent)
    DWM DPI Scaling: Disabled
     DxDiag Version: 6.01.7601.17514 32bit Unicode

**Comment by gzlee1985** [comment]
手机翻墙  APP 有点问题 之前已经在TG了

**Comment by meooxx** [comment]
> 手机翻墙 APP 有点问题 之前已经在TG了

稍等， 我用windows 编译下看看

**Comment by meooxx** [comment]
@gzlee1985 试下这个呢？
[yuyue-setup-386-bywin10.exe.zip](https://github.com/xxxXXX95/yuyue/files/7691816/yuyue-setup-386-bywin10.exe.zip)

**Comment by gzlee1985** [comment]
可以了  感谢
