### ISSUE TITLE
这个能不能导入CK的  还是只能扫码

### ISSUE THREAD

**Issue by gzlee1985** [meooxx/jd_yuyue#39]
是否能导入CK  呢？

**Comment by meooxx** [comment]
'''
或者你已经从别处获取到了cookie, 请至cookie.json(没有则新建一个)粘贴, 格式"key1=value1;key2=value2;"
'''


参考第七条

**Comment by gzlee1985** [comment]
本人比较笨 获取的CK   和 cookie.json  内的  不一样的  不知道如何添加多个CK 进去

**Comment by gzlee1985** [comment]
获取的 CK  是 APP 端 或者M端CK

**Comment by meooxx** [comment]
都支持，会分别解析的。
m或者pc端的cookie.
不支持多个cookie

**Comment by gzlee1985** [comment]
cookie.json  里面用 APP端CK  还是不会     例如我的CK  pin=jd_pMZleBWYkJBR;wskey=AAJhhUCIAED9mfzRKODxum6j6rma99K5U085BfQL-bMq7nS04xfcjHyWCZXNPQQ4xCGDRaSWDcPCc1r3EQLnCLetjUZMn-Zm;whwswswws=ppyoHkXoFQvXEdsGRZVydrz/StQKesegrHy6nlLgSH+VF75a4+5YcjMS7CQp984qlx/Dei/nRW9BuzPV5IRcfy/qiZ5LTOy2r5zZOUeSJHws21rfeNlUsnEaIY9kfLfHW;unionwsws=
如何 弄呢？

**Comment by meooxx** [comment]
"wskey=AAJhhUCIAED9mfzRKODxum6j6rma99K5U085BfQL-bMq7nS04xfcjHyWCZXNPQQ4xCGDRaSWDcPCc1r3EQLnCLetjUZMn-Zm;whwswswws=ppyoHkXoFQvXEdsGRZVydrz/StQKesegrHy6nlLgSH+VF75a4+5YcjMS7CQp984qlx/Dei/nRW9BuzPV5IRcfy/qiZ5LTOy2r5zZOUeSJHws21rfeNlUsnEaIY9kfLfHW;"

加英文双引号就可以了，如上面

**Comment by gzlee1985** [comment]
还是提示要扫码

**Comment by gzlee1985** [comment]
没有报错  提示要扫码是不是要改一下其他文件？

**Comment by gzlee1985** [comment]
process.master: 3088
progress.worker:login 6424
如果你是windows系统终端二维码现实有问题, 请打开本地目录新生成到qrcode.png 扫码
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

**Comment by meooxx** [comment]
加tg群 文件发给我，我试一下

**Comment by meooxx** [comment]
或者邮件地址贴出来，我给你发邮件，你回复

**Comment by meooxx** [comment]
m站和pc端 cookie 不通用
