### ISSUE TITLE
怎么让服务常驻

### ISSUE THREAD

**Issue by ocn1004** [meooxx/jd_yuyue#4]
用PM2或者forever会无限开启新的node 不是很懂这方面的 是因为代码用了node自带的cluster吗

**Comment by meooxx** [comment]
老哥， 具体需求是什么？ 为什么要用pm2? 我自己本地pm2 运行把我电脑都搞挂了。 代码里面有文件 io ， 应该是问题所在。
最好也别放在后台， 因为这个脚本就是一个抢购脚本， 开一个终端tab放着，方便随时开关，也方便看运行过程中出了什么问题好及时处理。 
如果非要后台运行， 执行`node index &` 就行了(linux 和 mac)。

**Comment by ocn1004** [comment]
> 老哥， 具体需求是什么？ 为什么要用pm2? 我自己本地pm2 运行把我电脑都搞挂了。 代码里面有文件 io ， 应该是问题所在。
> 最好也别放在后台， 因为这个脚本就是一个抢购脚本， 开一个终端tab放着，方便随时开关，也方便看运行过程中出了什么问题好及时处理。
> 如果非要后台运行， 执行`node index &` 就行了(linux 和 mac)。

因为有时可能抢购的那个时间点人不在电脑旁 无法操作 我就想能不能挂在服务器来着
回头我再试试看 谢了老哥
