### ISSUE TITLE
抢购的时间设置应该设置多少

### ISSUE THREAD

**Issue by THEWIND521** [meooxx/jd_yuyue#9]
我设置的是59秒600    具体抢购的时间点软件设置的逻辑是什么   我应该设置成多少呢？谢谢啦！

**Comment by THEWIND521** [comment]
PS C:\D\maotai\jd_yuyue-master\jd_yuyue-master> node index
main progress
progress.worker login 19320
cookie有效
progress.worker: 19928 时间: 1610675999600 sku 100012043978

**Comment by THEWIND521** [comment]
这个是不是有点问题呢？

**Comment by meooxx** [comment]
![image](https://user-images.githubusercontent.com/13815865/104548499-e9dd0e80-566b-11eb-8f1b-0bff00416e69.png)
以此图举例， 我实际设置了9, 59, 59, 300， 但是脚本运行了第9次后才获取到抢购链接， 每次间隔100ms
此时就可以估算出了我的本地时间大概比京东快了100ms， 所以我下次就可以设置9, 59, 59, 800 左右
只要比jd时间提前一点就可以的。 目前没办法跟jd精准同步的。

ps: 多次请求中最快的一次与服务器时间差(根据这个值设置提前多少ms开始), -116 看来这个值是准确的

**Comment by meooxx** [comment]
> 这个是不是有点问题呢？

没问题，非常ok， 昨晚我改进流程， 用了俩个timer 第一个timer负责到开抢前 1分钟，用于准确获取流程
第二个timer负责开抢一分钟前，调用具体流程

**Comment by THEWIND521** [comment]
那岂不是说不用等到开抢前几秒就才开  提前十几分钟开着就行了 到时间自动获取抢购的具体参数决定实施什么样的抢购  给你一个赞！今天的显卡一根毛都没碰上 我明天试试

**Comment by THEWIND521** [comment]
我参考了一些其他的脚本，你看下他这个时间获取的是不是准确的呢？

**Comment by THEWIND521** [comment]
2021-01-14 13:36:35.908 [34mINFO[0m   本地系统时间：2021-01-14 13:36:35.908 +0800 CST
2021-01-14 13:36:35.954 [34mINFO[0m   京东云端时间：2021-01-14 13:36:36.167 +0800 CST
2021-01-14 13:36:35.955 [34mINFO[0m   网络请求延时：47ms
2021-01-14 13:36:35.955 [34mINFO[0m   实际时间误差：-236ms (本地时间-京东云端时间+网络请求延时/2)

**Comment by meooxx** [comment]
> 2021-01-14 13:36:35.908 �[34mINFO�[0m 本地系统时间：2021-01-14 13:36:35.908 +0800 CST
> 2021-01-14 13:36:35.954 �[34mINFO�[0m 京东云端时间：2021-01-14 13:36:36.167 +0800 CST
> 2021-01-14 13:36:35.955 �[34mINFO�[0m 网络请求延时：47ms
> 2021-01-14 13:36:35.955 �[34mINFO�[0m 实际时间误差：-236ms (本地时间-京东云端时间+网络请求延时/2)

差不多，都不准的。 
1 这只是一次请求，一次请求误差较大。 我自己实现的是一次并发三次，取最低值。 但是这个值也只能参考
2 实际设置的话，最好根据这个值提前一点

**Comment by mendylove** [comment]
抢购几次自动停止？今天看抢购10：01分就停了。

**Comment by meooxx** [comment]
> 抢购几次自动停止？今天看抢购10：01分就停了。

抢购20次， 间隔300ms， 京东那边也会限制频率好像是 2s。
次数太少的话， 自己修改吧

**Comment by meooxx** [comment]
![image](https://user-images.githubusercontent.com/13815865/104550233-5c9bb900-566f-11eb-86c5-60a79d1a021d.png)
![image](https://user-images.githubusercontent.com/13815865/104550283-763d0080-566f-11eb-8bb3-4d576daf1a2a.png)

**Comment by THEWIND521** [comment]
我明天多复制几个文件夹 多开几个窗口抢  明天会放好多个3080

**Comment by meooxx** [comment]
> 我明天多复制几个文件夹 多开几个窗口抢 明天会放好多个3080

弱弱告诉你没用的, 本身支持多个skuId， 但是京东系统不支持哦。
因为添加到购物车流程会把购物车勾选项目合并到一个订单结算页面， 如果设置多个sku的话，多个进程访问同一个结算页面，只会有一个订单生成成功，其他进程就会报错， 会增加失败几率

**Comment by meooxx** [comment]
你这倒是提醒我了， 可以合并相同抢购流程的商品👍

**Comment by THEWIND521** [comment]
哭了，那明天那么多机会 该怎么抢啊。。。。万一选个没货的 岂不是白白浪费一次机会

**Comment by meooxx** [comment]
> 哭了，那明天那么多机会 该怎么抢啊。。。。万一选个没货的 岂不是白白浪费一次机会

预算内，抢最高价的显卡。

**Comment by meooxx** [comment]
双十一配件买了一堆， 显卡等到现在

**Comment by THEWIND521** [comment]
因为有的显卡根本就不放货 我怕堵错了 堵成不放货的了
